server:
  port : 8081

spring:
  application:
    name: linksbox
    
  profiles:
    active: local
      
  jmx:
    default-domain: ${spring.application.name}
       
  jackson:
    default-property-inclusion: NON_NULL
    
#  datasource:
#    hikari:
#      maximum-pool-size: 4  
#    url: "jdbc:postgresql://localhost:5432/postgres?ApplicationName=${spring.application.name}&currentSchema=${info.database.schema-name}"
#    username: postgres
#    password: habib 
    
#  datasource:
#    hikari:
#      maximum-pool-size: 4  
#    url: "jdbc:postgresql://ruby.db.elephantsql.com:5432/nuitqmxg?user=nuitqmxg&password=Qx47vcI1kx3ztodoLphsEmLFjI5xLQ93&sslmode=require"
#    username: nuitqmxg
#    password: Qx47vcI1kx3ztodoLphsEmLFjI5xLQ93  

  datasource:
    hikari:
      maximum-pool-size: 4  
    url: "jdbc:postgresql://ruby.db.elephantsql.com:5432/nuitqmxg?user=nuitqmxg&password=Qx47vcI1kx3ztodoLphsEmLFjI5xLQ93"
    username: nuitqmxg
    password: Qx47vcI1kx3ztodoLphsEmLFjI5xLQ93
    
#  datasource:
#    url: jdbc:h2:mem:linksbox
#    driverClassName: org.h2.Driver

  jpa: 
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
    properties:
        jdbc:
          lob:
            non_contextual_creation: true 

info:
  database:
    schema-name: linksbox