openapi: 3.0.1
info:
  title: LinksBox API
  version: '1.0'
servers:
  - url: 'https://linksbox-api.herokuapp.com/api/v1'
    description: dev
  - url: 'http://localhost:8081/api/v1'
    description: local  
  
paths:
  /links:  
    get:
      summary: Get list of all links
      operationId: getLinks  
      tags:
        - Links
      parameters:
      - name: tagUuids
        in: query
        required: false
        schema:
          type: array
          items:
            type: string 
            format: uuid 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LinkData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                     
    post:
      summary: Create new Link
      operationId: createLink
      tags:
        - Links 
      parameters:
      - name: tagUuids
        in: query
        required: true
        schema:
          type: array
          items:
            type: string 
            format: uuid        
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                
  /links/{uuid}:
    parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
          
    get:
      summary: Get link by given uuid
      operationId: getLinkByUuid
      tags:
        - Links
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                   
    put:
      summary: Update a link
      operationId: updateLink
      tags:
        - Links
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkInput'  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                      
    delete:
      summary: Delete link by given uuid
      operationId: deleteLink
      tags:
        - Links
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   

  /links/search/{searchText}:
    parameters:
      - name: searchText
        in: path
        required: true
        schema:
          type: string
          
    get:
      summary: Get link by given free text
      operationId: search
      tags:
        - Links
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LinkData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"
                                
  /tags:
    get:
      summary: Get list of all tags
      operationId: getTags  
      tags:
        - Tags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagData'
      
    post:
      summary: Create new Tag
      operationId: createTag
      tags:
        - Tags      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"        

  /tags/{uuid}:
    parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
          
    get:
      summary: Get tag by given uuid
      operationId: getTagByUuid
      tags:
        - Tags
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"                   
      
    put:
      summary: Update a tag
      operationId: updateTag
      tags:
        - Tags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagInput'  
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                      
    delete:
      summary: Delete tag by given uuid
      operationId: deleteTag
      tags:
        - Tags
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorList'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorList"   
                          
#################### COMPONENTS                
components:
  schemas:
  
    LinkData:
      type: object
      allOf:
        - $ref: '#/components/schemas/LinkInput'
        - properties:
            uuid:
              type: string
              format: uuid
            tags:
              type: array
              items:
                $ref: '#/components/schemas/TagData'  
          
    LinkInput:
      type: object
      required:
        - url
      properties:
        title:
          type: string
        url:
          type: string
        notes:
          type: string 

    TagData:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string  
        
    TagInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
      
    ApiError:
      required:
        - message
      properties:
        message:
          type: string
          
    ApiErrorList:
      type: array
      items:
        $ref: '#/components/schemas/ApiError'     